### ISSUE TITLE
Why are interface's vtables hashtables instead of arrays?

### ISSUE THREAD

**Issue by tomprimozic** [scross99/locic#1]
Hi!

I couldn't find your email, so I'm opening an issue instead.

I was wondering why are vtables implemented as hashtables, instead of as arrays, as in C++? I'm sure there is a good explanation, but I just don't see it (unless they're used for dynamically-typed dynamic dispatch, as in Objective-C).

Thanks!

**Comment by scross99** [comment]
Hi,

This is a great question and I realise the documentation needs to be updated to explain this.

The point is that you can have code such as:

```
class TestClass {
    void doFirstThing();
    void doSecondThing();
    void doThirdThing();
}

interface DoFirstInterface {
    void doFirstThing();
}

interface DoFirstAndSecondInterface {
    void doFirstThing();
    void doSecondThing();
}
```

(Ignore the bad names!)

Due to [Structural Typing](http://loci-lang.org/StructuralTyping.html), it's possible to cast a class reference type to any interface reference type, where the class contains all the methods needed for the interface. Furthermore it's possible to cast an interface reference type to another interface reference type, assuming the methods of the second interface form a subset of the methods of the first interface.

In the above case, it's possible to do the following casts:

```
TestClass -> DoFirstAndSecondInterface
TestClass -> DoFirstInterface
DoFirstAndSecondInterface -> DoFirstInterface
TestClass -> DoFirstAndSecondInterface -> DoFirstInterface
```

The last one is a path of two casts (e.g. function F creates TestClass, function G takes a reference to DoFirstAndSecondInterface and then calls function H, which takes a reference to DoFirstInterface).

This approach is different to most statically typed languages (such as C++) in which a class *explicitly* implements an interface; here classes *implicitly* implement any interfaces that are a subset of their methods. In the design stages I considered the tradeoff of a more complex implementation (though I argue on [DynamicDispatch](http://loci-lang.org/DynamicDispatch.html) that the performance should match C++ in most cases) versus the flexibility gained in the language, ultimately deciding that it was a very worthwhile feature.

Now you could have code like:

```
void takeSomeActions(DoFirstAndSecondInterface& object) {
    object.doFirstThing();
    object.doSecondThing();
}
```

This could be a public API function of a [Module](http://loci-lang.org/Modules.html), and as such this code is compiled without any knowledge of what the objects are, other than that they satisfy the interface specified. Hence for each of the two virtual calls here there needs to be a mechanism for being able to call the methods for any class, taking in consideration that there may have been a complex set of casts up to this point:

```
TestClass -> InterfaceA -> InterfaceB -> InterfaceC -> etc...
```

The hash table implementation was chosen since I believe it provides the best performance characteristics for the common cases (i.e. interfaces with a relatively small number of methods); it also doesn't require modifications to the vtable pointer as part of casting operations. Using a simple array as in C++ wouldn't work because, considering the above case, the compiler wouldn't know what offsets to generate for virtual calls that would satisfy all possible classes (some classes may have many methods, some have few, there could be long paths of upcasts).

Hopefully this is a reasonably helpful explanation and makes sense. I'd be very happy to answer any further questions.

Thanks,
Stephen

**Comment by tomprimozic** [comment]
Aha, so the difference I see is in this case:

    TestClass -> InterfaceA -> InterfaceB

In case of hashtables, you only need to build a vtable for the first cast (`TestClass -> InterfaceA`), whereas a single vtable is acceptable for all interfaces (as long as the correct methods are implemented).

In case of arrays, you would need to build a vtable for the first cast, by taking the methods of `TestClass` (statically determined) and putting them in an array in a predefined order. For the second cast, you would need to re-build the vtable, by taking the `InterfaceA`'s vtable, and putting  the methods that also belong to `InterfaceB` into a new vtable.

So the arrays would increase the overhead of interface-to-interface casts, while reducing the overhead of interface function calls. I guess the choice is then mostly the decision about which case to optimize.

Except in the case of polymorphic contrainters; for example, with hashtables and `list[InterfaceA]` is always a subtype of `list[InterfaceB]`, whereas with array vtables you would need to build a new listwith new vtables appropriate for `InterfaceB`. However, in neither case is a `list[TestClass]` a subtype of `list[InterfaceA]`. Does this apply to Loci?

**Comment by scross99** [comment]
Yes, it would be possible to do something more complex on casts from one interface reference type to another, however note that this would require a heap allocation (at least, I can't see any way to avoid a heap allocation). As you said, there are various trade-offs and I've tried to make decisions that have the best performance characteristics for the common use cases and to support the language features (designing a language is hard! :smile: ).

In response to your second point, you certainly can't do the following cast:

```
std::varray<TestClass&>& -> std::varray<Interface&>&
```

(Unlike C++ you can put references inside containers. Also note that 'std::varray' is essentially Loci's equivalent of C++'s 'std::vector'.)

Clearly the point here is that after the cast you could store a reference to an Interface& in the array that would actually not be a TestClass, essentially breaking the type system. It's slightly messy with the references inside the container, since obviously a container value type couldn't be an interface and must be a concrete type (so `std::varray<Interface>` is an invalid type).

Of course, you can do (theoretically in the language! I believe the compiler doesn't support this yet, but will very soon):

```
template <typename T>
interface ReadableArray {
    T& index(size_t index) noexcept;
}

template <typename T>
class Array {
    T& index(size_t index) noexcept;
}

void f() {
    auto array = Array<TestClass&>();
    g(array);
}

void g(ReadableArray<Interface&>& readableArray) {
    // Some code, such as:
    readableArray[0].doSomething();
}
```

The cast is valid since it uses the covariance of the reference type returned by index() (and structural typing is also based around covariance and contravariance of methods!).

You'll note I haven't used the standard library array class in this case because its index method returns an lvalue and that doesn't support covariance (since the lvalue type is assignable). I'm sure I'll be looking at this further in future to make this case work nicely (it seems like a const lvalue should be covariant), but currently there are more commonly-used aspects of the language that need addressing.
