### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by romix** [scross99/locic#2]
It would be nice if you could include some benchmarks as part of the repository. This would make it easier to compare Loci with other languages.

**Comment by romix** [comment]
In the meantime, could you spent a few words about performance of Loki vs other languages? In particular, it would be interesting to hear how it scores in arithmetic, array operations, OOP-heavy workloads (a lot of method invocations, inheritance, interfaces), method invocations dispatching, memory allocation, etc.  Do you have any numbers to post here? Thanks!

**Comment by scross99** [comment]
Hi,

This is a great suggestion and definitely something I'll look into soon (I'm releasing 1.2 in the next few weeks so I might find some time for some basic benchmarks).

I would note that:

* The language is on the same 'level' as C and C++; it's a compiled statically typed language, it uses stack allocations, it provides flexibility for performance gains (e.g. eliminating asserts, forcing casts, etc.), so can be expected to generally match these languages.
* The standard libraries are generally built on platform functionality. For example you mention memory allocations but this is essentially a test of malloc(), which is the underlying implementation of std.memory.
* The compiler generates LLVM IR, which means the LLVM optimisation pipeline can be used. Hence despite the language being new you can actually expect production-level performance characteristics comparable to Clang (a C++ frontend that generates LLVM IR).

Having said that, there are some language differences in Loci that affect the performance of programs (e.g. a slightly different dynamic dispatch mechanism) as well as their size. It's probably a good idea for me to port some of the programs from the [Computer Language 
Benchmarks Game](http://benchmarksgame.alioth.debian.org/) to Loci, so that there is equivalent code from other languages to test against. Note that, as discussed on that link, a small set of benchmarks provide a limited amount of information and so you can only really know the benefits/costs of a language for you by testing on your workload and your target hardware.

A big benefit of Loci is that the *compile times* are substantially reduced (primarily due to the differences in templates and simpler semantics) and this is something that I'm really keen to benchmark to compare against C++ compilers for equivalent C++ code.

Thanks for your comment!
Stephen
