### ISSUE TITLE
compilation error with LLVM 3.6

### ISSUE THREAD

**Issue by bdsatish** [scross99/locic#3]
Here's the error msg:

```
loci-src/lib/CodeGen/InternalContext.cpp:184:29: error: ‘const class llvm::TargetMachine’ has no member named ‘getDataLayout’
    return *(targetMachine().getDataLayout());
```

Seems LLVM have been shuffling around DataLayout (again)

**Comment by scross99** [comment]
Sorry for the delay (I waited until fixing the problems before responding).

I've fixed the build error you reported in 14226f796beedf16227902152591c5f31e49f386 and I then fixed the LLC crashes (due to opt inlining through a function without debug information) in 09b0348a04d66d6972ff02df7f44079440503285.

See here for the latest build outcome: https://travis-ci.org/scross99/locic/builds/55422033

**Comment by bdsatish** [comment]
Thanks. It compiles now. But I have a linker error:

````
/usr/bin/ld: cannot find -lcsfml-graphics
/usr/bin/ld: cannot find -lcsfml-window
/usr/bin/ld: cannot find -lcsfml-system
```

I know it is unrelated to this bug report, but still would like to ask what am I missing. I'm not interested in graphics or multimedia, so how do I disable CSFML / examples stuff during cmake invocation (other than commeting out in CMakeLists.txt) ?

**Comment by scross99** [comment]
Thanks for pointing this out; I should've fixed this a while back :smile: .

71be3488216a607522d810c5a297066b46b3fcdc should have fixed this problem so if you pull that and try re-building the relevant examples should be disabled.

**Comment by bdsatish** [comment]
Perfect. Thanks for the quick response

**Comment by scross99** [comment]
No problem :smiley:.
