### ISSUE TITLE
Couldn't `noexcept` be the default? Or automatic?

### ISSUE THREAD

**Issue by SuperV1234** [scross99/locic#4]
Not sure if this is the correct place to ask this question - sorry if it's out of scope for GitHub issues.
Anyway, my C++ code is riddled with `noexcept` specifications.

Exceptions are the "exception" (heh) in my code, not the norm. 
Wouldn't it make sense to tell the compiler when a function may throw, instead of the opposite?

Even better, wouldn't it be possible for the compiler to figure out if a function is `noexcept` automatically?
Example:

```
// ...
void test()
{
     throw SomeException();
}

// Compiler now knows that `test()` may throw because of the
// `throw` statement inside it

void test2()
{
    test();
}

// Compiler now knows that `test2()` may throw because of of a call
// to a function that can throw (`test()`) inside it

int test3()
{
    return 5 + 4;
}

// Compiler now knows that `test3()` will never throw because called
// statements inside it cannot throw.
```

**Comment by scross99** [comment]
Hi,

Thanks for your question.

(For other readers: relevant information is available at http://loci-lang.org/Exceptions.html )

> Not sure if this is the correct place to ask this question - sorry if it's out of scope for GitHub issues.

There will probably be a better place in future, but for now this is the right place.

> Exceptions are the "exception" (heh) in my code, not the norm. 
> Wouldn't it make sense to tell the compiler when a function may throw, instead of the opposite?

Exceptions certainly are not the normal case for code being executed, but from a static analysis point of view (i.e. the compiler looking at the code) it's actually normal that the vast majority of functions could throw. For example, any function that allocates memory, directly or indirectly, could potentially fail.

The addition of the `noexcept` keyword was taken with this consideration in mind; it's important to minimise verbosity and if most functions can throw, then it's more overhead for programmers on average if they have to write `throw(...)` for 90% of functions than if they write `noexcept` for 10% of functions.

Also note that writing `noexcept` is the programmer's choice - your non-throwing code still compiles and runs without the qualifier - whereas in the opposite situation writing `throw(...)` would be forced on the programmer for all their potentially-throwing code.

Another potentially serious issue is the effect `noexcept`-by-default would have on APIs (see [API versions](http://loci-lang.org/Modules.html#api-versions)): a function in an API may not be annotated and hence be `noexcept` by default, but it may later turn out that the function needs to throw (i.e. the programmer hadn't intended for the function API to be `noexcept`) and hence a new API version needs to be created. In the `noexcept`-by-choice case, the programmer would have to had explicitly mark the API as `noexcept` and hence would have (hopefully!) made a conscious decision that is likely to be more accurate than an implicit `noexcept`.

Finally, the language is likely to be of most interest to C++ developers. It would be extremely jarring for them to find code that looks very similar to C++ but has subtly and yet substantially different semantics. Where semantics vary from existing languages like C++ I've generally chosen to use new syntax to make this clear, so that when developers come to the language they are able to use and build on their intuition from working with other languages.

As a side note, your suggestion sounds somewhat like Java's checked exceptions and if so I'd suggest reading about all the problems that developers have experienced with them.

> Even better, wouldn't it be possible for the compiler to figure out if a function is `noexcept` automatically?

Primarily the `noexcept` qualifier exists as a static analysis tool for the programmer, so if they mark a function as `noexcept` which could actually throw the compiler will complain. Hence they can be sure that the function really cannot throw. An automatically-detected `noexcept` wouldn't have this advantage, since by definition it would only mark functions already known to be `noexcept` (though see below for how it can help satisfy `noexcept` qualifiers).

A second advantage of `noexcept` is in terms of performance (which in this case mostly means binary size; time overhead for exceptions is normally near zero). This is only important on API boundaries because optimisations can't see across these boundaries (unless you use link-time optimisation - optimise after linking the two modules together) so by marking an API function `noexcept` the optimisations can assume you're being honest.

And this is an important point: the Loci compiler is a front-end that emits LLVM IR, meaning your code is passed through a production-quality set of optimisations that *DO* add `noexcept` qualifiers (though LLVM's equivalent is called 'nounwind') to functions that are detected to not throw. So as long as you mark `noexcept` on the functions at API boundaries you'll ultimately have the same generated code as if you'd marked every function as `noexcept`.

So that's the key issue here: `noexcept` really exists a static analysis tool to help you the programmer ensure the correctness of your code. While it does aid optimisation in some cases this is largely already handled by the underlying system.

That said, there's an additional and very relevant aspect of this that you may have been considering. For example:

```
int f() {
    return 1 + 2;
}

int g() noexcept {
    return f();
}
```

In this case the compiler will (currently) complain that `noexcept` g() calls a potentially-throwing f(), even though it can quite clearly be seen that f() doesn't throw. It's debatable whether this code should be accepted or an explicit annotation should be required (what do you think?), but I'd personally think the compiler should accept this and will hence probably make the relevant change to the compiler at some point (it's a fairly simple change).

Note that the situation above is *radically* different to:

```
import {
    int f();
}

int g() noexcept {
    return f();
}
```

In this case the compiler can't see the source code of f() and hence must be conservative and assume the worst (i.e. that f() throws).

Hopefully this answer is helpful and the reasons given make sense; I'd be interested to know what you think. If you have any further questions then I'd be happy to answer them.

Thanks,
Stephen
